# Generated by Django 5.2 on 2025-07-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comentarios_nombre_comentarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='nombre',
        ),
    ]
